version: '3.4'

services:
  artur_gde_krosi_vue.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      # - ASPNETCORE_ENVIRONMENT=Production 
      - ASPNETCORE_HTTP_PORTS=5000:5000
      # - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=6000
    ports:
      - "5000:5000"
    volumes:  
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro